### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by axx0** [modern-forms/Modern.Forms#40]
I'm making an app with Modern forms and drawing a border on a panel with `OnPaintBackground`.
```

public class Mypanel : Panel 
{

        public Mypanel(int width, int height)
        {
            Width = width;
            Height = height;
        }

        protected override void OnPaintBackground(PaintEventArgs e)
        {
            base.OnPaintBackground(e);

            e.Canvas.Clear(SKColors.Black);

            // Outer wallpaper
            var img = MapImages.PanelOuterWallpaper;
            for (int row = 0; row <= Size.Height / img.Height; row++)
            {
                for (int col = 0; col <= Size.Width / img.Width; col++)
                {
                    e.Canvas.DrawBitmap(img, new SKPoint(col * img.Width, row * img.Height));
                }
            }

            // Paint panel borders
            // Outer border
            var paint1 = new SKPaint { Color = new SKColor(227, 227, 227) };
            var paint2 = new SKPaint { Color = new SKColor(105, 105, 105) };
            var paint3 = new SKPaint { Color = new SKColor(255, 255, 255) };
            var paint4 = new SKPaint { Color = new SKColor(160, 160, 160) };
            var paint5 = new SKPaint { Color = new SKColor(240, 240, 240) };
            var paint6 = new SKPaint { Color = new SKColor(223, 223, 223) };
            var paint7 = new SKPaint { Color = new SKColor(67, 67, 67) };
            e.Canvas.DrawLine(new SKPoint(0, 0), new SKPoint(Size.Width - 2, 0), paint1);
            e.Canvas.DrawLine(new SKPoint(0, 0), new SKPoint(0, Size.Height - 2), paint1);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 1, 0), new SKPoint(Size.Width - 1, Size.Height - 1), paint2);
            e.Canvas.DrawLine(new SKPoint(0, Size.Height - 1), new SKPoint(Size.Width - 1, Size.Height - 1), paint2);
            e.Canvas.DrawLine(new SKPoint(1, 1), new SKPoint(Size.Width - 3, 1), paint3);
            e.Canvas.DrawLine(new SKPoint(1, 1), new SKPoint(1, Size.Height - 3), paint3);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 2, 1), new SKPoint(Size.Width - 2, Size.Height - 2), paint4);
            e.Canvas.DrawLine(new SKPoint(1, Size.Height - 2), new SKPoint(Size.Width - 2, Size.Height - 2), paint4);
            e.Canvas.DrawLine(new SKPoint(2, 2), new SKPoint(Size.Width - 4, 2), paint5);
            e.Canvas.DrawLine(new SKPoint(2, 2), new SKPoint(2, Size.Height - 4), paint5);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 3, 2), new SKPoint(Size.Width - 3, Size.Height - 3), paint5);
            e.Canvas.DrawLine(new SKPoint(2, Size.Height - 3), new SKPoint(Size.Width - 3, Size.Height - 3), paint5);
            e.Canvas.DrawLine(new SKPoint(3, 3), new SKPoint(Size.Width - 5, 3), paint6);
            e.Canvas.DrawLine(new SKPoint(3, 3), new SKPoint(3, Size.Height - 5), paint6);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 4, 3), new SKPoint(Size.Width - 4, Size.Height - 4), paint7);
            e.Canvas.DrawLine(new SKPoint(3, Size.Height - 4), new SKPoint(Size.Width - 4, Size.Height - 4), paint7);
            e.Canvas.DrawLine(new SKPoint(4, 4), new SKPoint(Size.Width - 6, 4), paint6);
            e.Canvas.DrawLine(new SKPoint(4, 4), new SKPoint(4, Size.Height - 6), paint6);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 5, 4), new SKPoint(Size.Width - 5, Size.Height - 5), paint7);
            
            // Inner border
            e.Canvas.DrawLine(new SKPoint(9, 12 - 1), new SKPoint(9 + (Size.Width - 18 - 1), 12 - 1), paint7);
            e.Canvas.DrawLine(new SKPoint(10, 12 - 1), new SKPoint(10, Size.Height - 12 - 1), paint7);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 11, 12 - 1), new SKPoint(Size.Width - 11, Size.Height - 12 - 1), paint6);
            e.Canvas.DrawLine(new SKPoint(9, Size.Height - 12), new SKPoint(Size.Width - 9 - 1, Size.Height - 12), paint6);
            e.Canvas.DrawLine(new SKPoint(10, 12 - 2), new SKPoint(9 + (Size.Width - 18 - 2), 12 - 2), paint7);
            e.Canvas.DrawLine(new SKPoint(9, 12 - 2), new SKPoint(9, Size.Height - 12), paint7);
            e.Canvas.DrawLine(new SKPoint(Size.Width - 10, 12 - 2), new SKPoint(Size.Width - 10, Size.Height - 12), paint6);
            e.Canvas.DrawLine(new SKPoint(9, Size.Height - 12 + 1), new SKPoint(Size.Width - 9 - 1, Size.Height - 12+ 1), paint6);
        }
```

When I run the program I get the following error in Program.cs:
![image](https://user-images.githubusercontent.com/21365802/193622838-1d1b3c92-6dc6-4b86-b423-9fd3d3b0495e.png)

However when I comment out a part of the `e.Canvas.DrawLine` statements above, the program runs smoothly. Any clue what could be causing this?

**Comment by jpobst** [comment]
You will likely need to click "View Details" in order to see the entire error message.

**Comment by axx0** [comment]
Here are the details:

System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Modern.Forms.ControlAdapter.OnPaint(PaintEventArgs e)
   at Modern.Forms.Control.RaisePaint(PaintEventArgs e)
   at Modern.Forms.WindowBase.DoPaint(Rect r)
   at Modern.WindowKit.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Modern.WindowKit.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

![image](https://user-images.githubusercontent.com/21365802/193666093-f1663001-416a-4aa6-a296-e99e0e223dcc.png)

**Comment by jpobst** [comment]
The code in `Modern.Forms` is:

```csharp
foreach (var control in Controls.GetAllControls ().Where (c => c.Visible)) {
    if (control.Width <= 0 || control.Height <= 0)
        continue;

    var info = new SKImageInfo (control.Width, control.Height, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
    var buffer = control.GetBackBuffer ();

    if (control.NeedsPaint) {
        using (var canvas = new SKCanvas (buffer)) {
            // start drawing
            var args = new PaintEventArgs(info, canvas, Scaling);

            control.RaisePaintBackground (args);
            control.RaisePaint (args);

            canvas.Flush ();
        }
    }

    e.Canvas.DrawBitmap (buffer, form_x + control.ScaledLeft, form_y + control.ScaledTop);
}
```

So it's looping through the `Controls` collection for your panel.  I don't see any issues in the code you posted, but something is either adding or removing Controls to the panel, or changing the `Visible` property of child controls.

I can also create a fix for this in `Modern.Forms` itself.
